// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJWZh_slHlJMPQiY2iP9p5PjmjC5AI9w',
    appId: '1:1024189385608:web:6499a1873a468fc049883d',
    messagingSenderId: '1024189385608',
    projectId: 'book-app-562ca',
    authDomain: 'book-app-562ca.firebaseapp.com',
    storageBucket: 'book-app-562ca.appspot.com',
    measurementId: 'G-Q212YVYG6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfG0oodad1-N-bK6rhYHlO7FzJFnoaWxI',
    appId: '1:1024189385608:android:62d8d157689d0ef749883d',
    messagingSenderId: '1024189385608',
    projectId: 'book-app-562ca',
    storageBucket: 'book-app-562ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0h5oypNQ1GTbTjq1GRuMqQfnNXCmsvog',
    appId: '1:1024189385608:ios:6d9ce2c1b6e5345549883d',
    messagingSenderId: '1024189385608',
    projectId: 'book-app-562ca',
    storageBucket: 'book-app-562ca.appspot.com',
    iosBundleId: 'com.example.booklyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0h5oypNQ1GTbTjq1GRuMqQfnNXCmsvog',
    appId: '1:1024189385608:ios:6d9ce2c1b6e5345549883d',
    messagingSenderId: '1024189385608',
    projectId: 'book-app-562ca',
    storageBucket: 'book-app-562ca.appspot.com',
    iosBundleId: 'com.example.booklyapp',
  );
}
